# Set Zsh as default shell
export SHELL=$(which zsh)

# Path setup
export PATH="/usr/local/bin:$HOME/bin:$HOME/.local/bin:/opt/homebrew/bin:/opt/homebrew/opt/maven/bin:/opt/homebrew/opt/openjdk@11/bin:$HOME/.jenv/bin:$GOPATH/bin:$GOROOT/bin:$PATH"

# Oh My Zsh setup
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"

# Enable Plugins
plugins=(
    git
    npm
    zsh-autosuggestions
    zsh-syntax-highlighting
)

# Load Oh My Zsh
source $ZSH/oh-my-zsh.sh

# # Useful Aliases
# alias zshconfig="vim ~/.zshrc"
# alias ohmyzsh="vim ~/.oh-my-zsh"

# Source iTerm2 shell integration if exists
test -e "\${HOME}/.iterm2_shell_integration.zsh" && source "\${HOME}/.iterm2_shell_integration.zsh" || true
POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true