# Set Zsh as default shell
export SHELL=\$(which zsh)

# Path setup
export PATH="/usr/local/bin:$HOME/bin:$HOME/.local/bin:/opt/homebrew/bin:/opt/homebrew/opt/maven/bin:/opt/homebrew/opt/openjdk@11/bin:$HOME/.jenv/bin:$GOPATH/bin:$GOROOT/bin:$PATH"

# Oh My Zsh setup
export ZSH="\$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"

# Enable Plugins
plugins=(
    git
    npm
    zsh-autosuggestions
    zsh-syntax-highlighting
)

# Plugins
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Load Oh My Zsh
source \$ZSH/oh-my-zsh.sh

# Enable Pyenv
alias python=python3
export PYENV_ROOT="\$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="\$PYENV_ROOT/bin:\$PATH"
eval "\$(pyenv init -)"

# Enable Jenv
export PATH="\$HOME/.jenv/bin:\$PATH"
eval "\$(jenv init -)"

# Enable Golang
export GOROOT=\$(brew --prefix go)/libexec
export GOPATH=\$HOME/go
export PATH=\$GOPATH/bin:\$GOROOT/bin:\$HOME/.local/bin:\$PATH

# Enable Kubectl auto-completion
if command -v kubectl &>/dev/null; then
  source <(kubectl completion zsh)
fi

# Useful Aliases
alias zshconfig="vim ~/.zshrc"
alias ohmyzsh="vim ~/.oh-my-zsh"

# Source iTerm2 shell integration if exists
test -e "\${HOME}/.iterm2_shell_integration.zsh" && source "\${HOME}/.iterm2_shell_integration.zsh" || true