#!/bin/bash

# Change default shell to Zsh (Uncomment if needed)
# chsh -s $(which zsh)

# Remove any existing Oh My Zsh setup
rm -rf ~/.oh-my-zsh

# Install Oh My Zsh *without exiting the session*
curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | zsh

# Remove the default .zshrc generated by Oh My Zsh
rm -f ~/.zshrc

# Ensure the new .zshrc is properly linked
ln -sf ~/.dev-setup/dotfiles/zshrc ~/.zshrc

# Install Plugins via Homebrew
brew install powerlevel10k

# Install Powerlevel10k
mkdir -p ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes
ln -sf $(brew --prefix)/share/powerlevel10k ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k

git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# Restart Zsh session properly
echo "Restart your terminal or run 'exec zsh' to apply changes."
