# Taps
tap "derailed/k9s"
tap "romkatv/powerlevel10k"

# Shells
brew "zsh"
brew "nushell"

# Shell utilities
brew "wget"
brew "tree"
brew "vim"

# Dev tools
brew "git"

# Containers
brew "colima"
brew "docker"
brew "derailed/k9s/k9s"
brew "argocd"
brew "kubectl"
brew "helm"

# Cloud CLIs
brew "awscli"
brew "azure-cli"

# Programming languages
brew "python"
brew "pyenv"
brew "go"
brew "rust"

# AI
brew "ollama"

# Applications
cask "iterm2"
cask "visual-studio-code"
cask "obsidian"
cask "arc"